### ISSUE TITLE
Fabric port

### ISSUE THREAD

**Issue by nco2k** [kara2810/NMPR---1.12#4]
would be cool if you could port your mod to fabric :)

**Comment by kara2810** [comment]
Not likely to happen for the following reasons:

* I retired from modding about 4 years ago
* I never used fabric, and I have no knowledge how to do it, plus porting it would require a total re-write.

That said if someone wishes to make a fabric version they are welcome to, but it won't involve me. The current maintainer may choose to do it at some point.

**Comment by Mrbysco** [comment]
There's now a Fabric version for 1.20.1 on Curseforge/Modrinth
